# Generated by Django 4.1 on 2023-11-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyects',
            name='involved_users',
        ),
        migrations.AlterField(
            model_name='proyects',
            name='begin_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyects',
            name='end_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
