# Generated by Django 4.1 on 2023-12-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyects',
            name='begin_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyects',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
