# Generated by Django 4.1 on 2023-12-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_proyects_begin_date_alter_proyects_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyects',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
