# Generated by Django 4.1 on 2023-12-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_proyects_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyects',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
