# Generated by Django 4.1 on 2023-11-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='occupation',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('institucion', 'Institución')], max_length=20, null=True),
        ),
    ]
