# Generated by Django 4.1 on 2023-12-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0002_alter_appuser_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
